Adds support for Azure AD
github/ldap-teamsync pull request #56
Opened 2021-03-22 04:32 UTC by primetheus

This PR adds support for Azure AD.

### Authentication methods
- [ ] Username/Password
- [x] Service Principal
- [ ] Certificate
- [ ] Device Auth

---
To use AzureAD, simply change `USER_DIRECTORY` to `AAD` and set the Azure settings

```env
## User directory to sync GitHub teams from
## Azure AD = AAD
## Active Directory = LDAP
## OpenLDAP = LDAP
USER_DIRECTORY=AAD

#######################
## Azure AD Settings ##
#######################
## Azure Tenant ID
AZURE_TENANT_ID="<tenant_id>"
## Azure Service Principal Client ID
AZURE_CLIENT_ID="<client_id>"
## Azure Service Principal Client Secret
AZURE_CLIENT_SECRET="<client_secret>"
## Azure AD directory scopes. If you have multiple directories, separate them by spaces
## i.e. "default github devteam"
AZURE_APP_SCOPE="default"
## API endpoint for Azure AD (Graph) group member queries
AZURE_API_ENDPOINT="https://graph.microsoft.com/v1.0"
## Custom attribute for usernames
USERNAME_ATTRIBUTE=userPrincipalName
```

2021-03-22 04:34 UTC, primetheus commented on githubapp/azuread.py
> +        for group in groups['value']:
@stoe this currently pulls _all_ groups and iterates over them. We'll need to add a filter to lookup a group and return the ID.

2021-03-22 04:34 UTC, primetheus commented on githubapp/azuread.py
> +    aad.get_group_members(token=token, group="0aafe564-0044-424c-8a75-e8a59e6a83d5")
this section can be deleted when the group filter is added... it's just for testing

2021-03-22 05:51 UTC, stoe submitted a review, later dismissed
LGTM

2021-03-22 08:33 UTC, stoe approved these changes

2021-03-23 06:57 UTC, stoe approved these changes
I'll give it a spin today.

2021-03-23 07:09 UTC, stoe requested changes
Should probably address the linter issues!?

2021-03-23 16:00 UTC, stoe approved these changes

2021-03-23 18:43 UTC, merged